---
- name: Deploy cockpit
  hosts: server01.th.lab
    
  tasks:
    - name: Ensure cockpit is installed
      ansible.builtin.yum:
        name: cockpit
        state: present

    - name: Ensure the cockpit is started and enabled
      ansible.builtin.systemd:
        name: cockpit
        state: started 
        enabled: true 

    - name: Ensure Cockpit network traffic is allowwd 
      ansible.posix.firewalld:
        service: cockpit
        permanent: true 
        state: enabled
        immediate: true 
